[package]
name = "shai_hulud_v2_checker"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
ureq = "3.1.4"
