name: Release rust app

on:
  push:
    tags:
      - "v[0-9].*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create GitHub Release üè∑Ô∏è
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check if release already exists üîç
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
          REPO_NAME: ${{ github.repository }}
        run: |
          set +e # Disable exit on error to handle the case where release does not exist

          is_created=false
          if gh release view "${TAG_NAME}" --repo "${REPO_NAME}"; then
            echo "::warning::Release for tag '${TAG_NAME}' already exists in repository '${REPO_NAME}' üö® Skipping release creation. We will proceed to upload assets."
            is_created=true
          fi

          echo "is_created=${is_created}" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release üöÄ
        if: steps.check_release.outputs.is_created == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
          REPO_NAME: ${{ github.repository }}
          CHANGELOG_PATH: CHANGELOG.md
        run: |
          if [ ! -f "$CHANGELOG_PATH" ]; then
            echo "::warning::Changelog file not found at path: $CHANGELOG_PATH, using default release notes."
            echo "Automated release for tag '${TAG_NAME}' üìù" > "$CHANGELOG_PATH"
          fi

          echo "::info::Generating release notes '${TAG_NAME}' from changelog at path: $CHANGELOG_PATH"
          gh release create "${TAG_NAME}" \
            --repo "${REPO_NAME}" \
            --title "${TAG_NAME}" \
            -F "${CHANGELOG_PATH}"

  upload:
    name: Build and Upload Binaries üì¶
    strategy:
      matrix:
        # you can list all the targets using:
        #   rustup target list
        # please make sure the os is able to build for the target
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            features: ""
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            features: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            features: ""

    runs-on: ${{ matrix.os }}
    needs: create-release
    env:
      BINARY_NAME: shai_hulud_v2_checker
    steps:
      - uses: actions/checkout@v5

      - name: Set up Rust üîß
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Format check üñåÔ∏è
        run: |
          cargo fmt --all -- --check

      - name: Linting üïµÔ∏è
        run: |
          cargo clippy --all-features -- -D warnings

      - name: Run tests üß™
        run: |
          cargo test --all-features

      - name: Build ‚öôÔ∏è
        env:
          TARGET: ${{ matrix.target }}
          FEATURES: ${{ matrix.features }}
        shell: bash
        run: |
          cargo build \
            --release \
            --locked \
            --features "${FEATURES}" \
            --target "${TARGET}"

      - name: Upload Release Binary üì¶
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET: ${{ matrix.target }}
          REPO_NAME: ${{ github.repository }}
          TAG_NAME: ${{ github.ref_name }}
          OS: ${{ matrix.os }}
        shell: bash
        run: |
          asset_path="target/${TARGET}/release"
          rust_binary_path="${asset_path}/${BINARY_NAME}"
          binary_full_name="${BINARY_NAME}_${TAG_NAME}_${TARGET}"
          windows_build=false

          if [[ "${OS}" =~ "windows" ]]; then
            rust_binary_path="${rust_binary_path}.exe"
            windows_build=true
          fi

          if [ ! -f "${rust_binary_path}" ]; then
            echo "::error::Built binary not found at path: '${rust_binary_path}'"
            exit 1
          fi

          if [ ${windows_build} = true ]; then
            binary_full_name="${binary_full_name}.exe"
            binary_compressed_name="${binary_full_name}.zip"
            mv "${rust_binary_path}" "${binary_full_name}"

            7z a -tzip "${binary_compressed_name}" "${binary_full_name}"
          else
            binary_compressed_name="${binary_full_name}.tar.gz"
            mv "${rust_binary_path}" "${binary_full_name}"

            tar -czf "${binary_compressed_name}" "${binary_full_name}"
          fi

          echo "::info::Uploading build artifact for target '${TARGET}' to release '${TAG_NAME}'"
          gh release upload "${TAG_NAME}" \
            --repo "${REPO_NAME}" \
            "${binary_compressed_name}" \
            --clobber
